environments:
  magenta:
    environment_variables:
      AWS_DEFAULT_REGION: eu-west-2
    pipelines:
      - magenta
pipelines:
  magenta:
    group: magenta
    label_template: "${magenta[:8]}"
    locking: off
    materials:
      magenta:
        git: https://github.com/clarkio/vulnerable-app.git
        branch: master
    stages:
      - Test:
          clean_workspace: true
          jobs:
            HelloWorld:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - "/usr/bin/docker run --rm -v $PWD:/target stono/hawkeye"
